<a href="https://colab.research.google.com/github/amit17133129/Body_Counter/blob/master/LogisticRegression10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np


In [49]:
data= pd.read_csv("/content/Indian-liver-patients.csv")
data

Age of the patient  ... Liver patient or not
0                    65  ...                    1
1                    62  ...                    1
2                    62  ...                    1
3                    58  ...                    1
4                    72  ...                    1
..                  ...  ...                  ...
578                  60  ...                    2
579                  40  ...                    1
580                  52  ...                    1
581                  31  ...                    1
582                  38  ...                    2

[583 rows x 11 columns]

In [50]:
data.isnull().sum()

Age of the patient                 0
Gender of the patient              0
Total Bilirubin                    0
Direct Bilirubin                   0
Alkphos Alkaline Phosphotase       0
Sgpt Alamine Aminotransferase      0
Sgot Aspartate Aminotransferase    0
Total Protiens                     0
Albumin                            0
Albumin and Globulin Ratio         4
Liver patient or not               0
dtype: int64

In [53]:
from sklearn.preprocessing import LabelEncoder
lb =LabelEncoder()
data['Albumin and Globulin Ratio'] = lb.fit_transform(data['Albumin and Globulin Ratio'])
data['Gender of the patient'] = lb.fit_transform(data['Gender of the patient'])
data.isnull().sum()
data.head()

Age of the patient  ...  Liver patient or not
0                  65  ...                     1
1                  62  ...                     1
2                  62  ...                     1
3                  58  ...                     1
4                  72  ...                     1

[5 rows x 11 columns]

In [54]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
X = data.iloc[:,1:10].values
y = data.iloc[:,-1].values

X,y

(array([[ 0. ,  0.7,  0.1, ...,  6.8,  3.3, 31. ],
        [ 1. , 10.9,  5.5, ...,  7.5,  3.2, 23. ],
        [ 1. ,  7.3,  4.1, ...,  7. ,  3.3, 30. ],
        ...,
        [ 1. ,  0.8,  0.2, ...,  6.4,  3.2, 37. ],
        [ 1. ,  1.3,  0.5, ...,  6.8,  3.4, 37. ],
        [ 1. ,  1. ,  0.3, ...,  7.3,  4.4, 56. ]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 1, 1, 1, 1,
        1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 2, 1,
        2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2,
        2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 2,
        2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 2,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 1, 1, 1,
        2, 1,

In [62]:
X_train, X_test, y_train, y_test= train_test_split(X,y, test_size=0.2)
model=LogisticRegression()
mk=model.fit(X_train,y_train)
mk

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [63]:
y_pred=model.predict(X_test)
y_pred

array([1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1,
       1, 1, 1, 1, 1, 1, 1])

In [85]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import r2_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))
print("Confusion_matrix:",confusion_matrix(y_test, y_pred))
print("Variance:",r2_score(y_test, y_pred))
print("F1_Score:",f1_score(y_test, y_pred))
print("Accutacy_score:",accuracy_score(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.72      0.95      0.82        81
           2       0.60      0.17      0.26        36

    accuracy                           0.71       117
   macro avg       0.66      0.56      0.54       117
weighted avg       0.68      0.71      0.65       117

Confusion_matrix: [[77  4]
 [30  6]]
Variance: -0.3641975308641976
F1_Score: 0.8191489361702128
Accutacy_score: 0.7094017094017094
