<a href="https://colab.research.google.com/github/amit17133129/Body_Counter/blob/master/Regression_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np
data=pd.read_csv("/content/heart.csv")
data.head(10)

age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1
5   57    1   0       140   192    0  ...      0      0.4      1   0     1       1
6   56    0   1       140   294    0  ...      0      1.3      1   0     2       1
7   44    1   1       120   263    0  ...      0      0.0      2   0     3       1
8   52    1   2       172   199    1  ...      0      0.5      2   0     3       1
9   57    1   2       150   168    0  ...      0      1.6      2   0     2       1

[10 rows x 14 columns]

In [25]:
data.shape

(303, 14)

In [26]:
X=data.iloc[:,0:13].values
y=data.iloc[:,-1].values

X,y

(array([[63.,  1.,  3., ...,  0.,  0.,  1.],
        [37.,  1.,  2., ...,  0.,  0.,  2.],
        [41.,  0.,  1., ...,  2.,  0.,  2.],
        ...,
        [68.,  1.,  0., ...,  1.,  2.,  3.],
        [57.,  1.,  0., ...,  1.,  1.,  3.],
        [57.,  0.,  1., ...,  1.,  1.,  2.]]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [0]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
X_train, X_test, y_train, y_test=train_test_split(X,y, test_size=0.2, random_state=0)


In [49]:
ridge=Ridge(alpha=10)
ridge.fit(X_train, y_train)


Ridge(alpha=10, copy_X=True, fit_intercept=True, max_iter=None, normalize=False,
      random_state=None, solver='auto', tol=0.001)

In [50]:
y_pred=ridge.predict(X_test)
y_pred

array([ 0.08728704,  0.7206164 ,  0.74333207,  0.0354922 ,  0.24479471,
        0.52529439,  0.19096216,  0.27306145, -0.1920306 , -0.20064958,
        0.66861245,  0.87028348,  0.10576846,  0.76743094,  0.96124192,
        0.64359196,  0.19114326,  0.67212048, -0.12818121,  0.77938421,
        0.72722875,  0.44801837,  0.24554256,  0.25597821,  0.80104102,
        0.54322603,  0.32749155,  0.48069997,  1.02585939,  0.60918005,
        0.61735651, -0.02591819,  0.9754032 ,  0.67093127,  0.86691013,
        0.56562042,  0.08923524,  0.78018917,  0.2143164 ,  0.28792852,
        0.66708089,  0.71060833,  0.43934601,  0.20367674,  0.53345723,
        0.64702552,  0.74796783,  0.60283101,  0.13854739,  0.74427961,
        0.79207867,  0.5569653 ,  0.99431892,  0.76449905,  1.22393362,
        0.26135786,  0.90322445,  0.85344994,  0.70135964,  0.92322563,
        0.67906454])

In [51]:

print("Training set score:{:.2f}".format(ridge.score(X_train, y_train)))

Training set score:0.52


In [52]:
print("Training set score:{:.2f}".format(ridge.score(X_test, y_test)))

Training set score:0.48
